### PR TITLE
Use Result's instead of unwrap and expect

### LINKED ISSUE #28: Never panic when parsing
Currently, the parser uses `unwrap` and `expect`, but it would be more Rust-like and improve usability to use a special error type everywhere.

This type could give detailed diagnostics about what went wrong. Does Pest provide something like this already?

### PR DESCRIPTION
**Pull request by mbudde**
Fixes #28

### CODE REVIEW

**Comment by mbudde** [comment]
@ThomasdenH, would be great if you could also take a look at this 🙂

File: beancount-parser/examples/dump_parse.rs [hunk 1]
```diff
@@ -1,9 +1,17 @@
...
+    let ledger = parse(&unparsed_file)?;
     dbg!(ledger);
+    Ok(())
+}
+
+fn main() {
+    match run() {
+        Err(e) => println!("Error: {}", e),
+        _ => {}
+    }
```
Comment (twilco) [inline beancount-parser/examples/dump_parse.rs:16]: Rust `main` functions can return results, so the logic in `run` can still be in `main`.

https://doc.rust-lang.org/edition-guide/rust-2018/error-handling-and-panics/question-mark-in-main-and-tests.html

File: beancount-parser/src/error.rs [hunk 2]
```diff
@@ -0,0 +1,186 @@
...
+            kind: ParseErrorKind::InvalidInput {
+                message: format!("{}", err),
+            },
+            location,
+            source: Some(Box::new(err)),
+        }
+    }
+}
+
+pub type ParseResult<T> = Result<T, ParseError>;
```
Comment (twilco) [inline beancount-parser/src/error.rs:186]: Not a blocking review comment, but in my experience it's nice to have type aliases towards the top since they're typically one-liners and are important in understanding the "headline" type-signature information.

File: beancount-parser/src/error.rs [hunk 3]
```diff
@@ -0,0 +1,186 @@
...
+use super::Rule;
+
+/// Details about a `BasicParseError`
+#[derive(Clone, Debug, PartialEq)]
+pub enum ParseErrorKind {
+    /// Input is invalid in some way
+    InvalidInput { message: String },
+    /// Parser has reached an invalid state (most likely a bug in the parser)
+    InvalidParserState { message: String },
+}
```
Comment (twilco) [inline beancount-parser/src/error.rs:15]: Below, we have a decimal parse error kind, but it is wrapped into the `InvalidInput` variant.  What are your thoughts on instead having an explicit `InvalidDecimal { message: String }` variant here?  We could still have a catch-all `InvalidInput` variant for any parse errors that don't fit into more explicit buckets.  This would give users more flexibility in their reaction to errors, e.g. "I want to explicitly handle the case for invalid decimals differently than other more general invalid input".

I personally like how Servo does this with its `StyleParseErrorKind`.  Note the other `InvalidValue` catch-all.  We probably won't have as many error types as Servo, so perhaps this is less important, but still could be useful for our users.

https://github.com/servo/servo/blob/30ca50ae985fca0c7f6a97bdad05921bb411cd3c/components/style_traits/lib.rs#L111#L170

I think `InvalidParserState` is also a good one to keep.

File: beancount-parser/src/error.rs [hunk 4]
```diff
@@ -0,0 +1,186 @@
...
+                Rule::num_prefix => "numeric prefix",
+                Rule::term => "numeric expression term",
+                Rule::amount => "an amount",
+                Rule::double_quote => "double quotation mark",
+                Rule::quoted_str => "a quoted string",
+                Rule::inner_quoted_str => "inner part of a quoted string",
+                Rule::quoted_char => "an (possibly escaped) character",
+                Rule::escape_sequence => "escape sequence",
+                Rule::valid_non_letter_commodity_char => "valid commodity non-letter character",
+                Rule::commodity_trailing => "commodity",
```
Comment (twilco) [inline beancount-parser/src/error.rs:114]: Is the "trailing" aspect here important for our users to know?  Or no?

```
Rule::commodity_trailing => "trailing commodity"
```

File: beancount-parser/src/error.rs [hunk 5]
```diff
@@ -0,0 +1,186 @@
...
+                Rule::multiply => "'*'",
+                Rule::divide => "'/'",
+                Rule::num_expr => "numeric expression",
+                Rule::num_prefix => "numeric prefix",
+                Rule::term => "numeric expression term",
+                Rule::amount => "an amount",
+                Rule::double_quote => "double quotation mark",
+                Rule::quoted_str => "a quoted string",
+                Rule::inner_quoted_str => "inner part of a quoted string",
+                Rule::quoted_char => "an (possibly escaped) character",
```
Comment (twilco) [inline beancount-parser/src/error.rs:111]: I believe this should be:

a (possibly escaped) character

File: beancount-parser/src/error.rs [hunk 6]
```diff
@@ -0,0 +1,186 @@
...
+                Rule::add => "'+'",
+                Rule::subtract => "'-'",
+                Rule::multiply => "'*'",
+                Rule::divide => "'/'",
+                Rule::num_expr => "numeric expression",
+                Rule::num_prefix => "numeric prefix",
+                Rule::term => "numeric expression term",
+                Rule::amount => "an amount",
+                Rule::double_quote => "double quotation mark",
+                Rule::quoted_str => "a quoted string",
```
Comment (twilco) [inline beancount-parser/src/error.rs:109]: In the name of consistency, does this need to be prefixed with `a ...`?  Or could it just be `quoted_string`?  I think prefixing this way makes sense for certain rules (e.g. `Rule::quoted_char` below), but maybe less so for this one?

It seems throughout this `Impl` that some things are prefixed with a/an and others aren't.  It could be good to be consistent here either way, when possible.

File: beancount-parser/examples/dump_parse.rs (hunk 1 above)
Comment (mbudde) [reply beancount-parser/examples/dump_parse.rs:16]: The reason I have done it this way is that I want the `Display` version printed, not the `Debug` version you get when raising an error in main.

File: beancount-parser/src/error.rs (hunk 6 above)
Comment (mbudde) [reply beancount-parser/src/error.rs:109]: Yeah, I haven't been consistent in that regard. I think I'll remove the prefix in most places where it isn't strictly necessary.

For many of these rules it doesn't seem possible to get them in an actual error message because they are part of another atomic rule, e.g. `double_quote`.

File: beancount-parser/src/error.rs (hunk 3 above)
Comment (mbudde) [reply beancount-parser/src/error.rs:16]: Yeah, having a separate `InvalidDecimal` error kind would probably be a good idea, since `rust_decimal` has limitations on the numbers it can represent.

File: beancount-parser/examples/dump_parse.rs (hunk 1 above)
Comment (ThomasdenH) [reply beancount-parser/examples/dump_parse.rs:16]: Since it's an example, it might be an idea to use `anyhow::Result` here.

File: beancount-parser/src/error.rs (hunk 3 above)
Comment (ThomasdenH) [reply beancount-parser/src/error.rs:18]: For `InvalidInput` I think a `&'static str` would work as well, that removes the need to allocate.

It would also be possible to directly expose the underlying decimal error and derive a `#[from]`, but I'm not sure that's desirable. It would become part of the public API, although `Decimal` already is.

Comment (mbudde) [reply beancount-parser/src/error.rs:18]: The message in `InvalidInput` is generated in the `From<pest::error::Error>` impl so can't see how it can be `'static`.

I didn't go for a `From<rust_decimal::Error> for ParseError` impl since that would mean that I don't get any span information. But I have added the decimal error as `source` on the `ParseError` like I do for pest errors.

Comment (ThomasdenH) [reply beancount-parser/src/error.rs:18]: Ah, perfect! I might be wrong, but I think all values for the message come directly from the match statement, right? But it's fine either way.
